# Generated by Django 2.0.7 on 2018-07-25 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='名称')),
                ('desc', models.TextField(verbose_name='描述')),
                ('status', models.IntegerField(choices=[(0, '草稿'), (1, '正常'), (2, '关闭')], default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('weight', models.IntegerField(default=0)),
                ('comment', models.CharField(blank=True, default='', max_length=256, verbose_name='备注')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='item_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目列表',
                'db_table': 'task_item',
                'ordering': ['-weight'],
            },
        ),
    ]
