# Generated by Django 2.0.7 on 2018-07-25 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(help_text='设备上贴的条码编号', max_length=64, verbose_name='序列号')),
                ('device_model', models.CharField(max_length=64, verbose_name='机型')),
                ('kind', models.IntegerField(choices=[(0, '手机'), (1, '笔记本'), (2, 'PC'), (3, 'Pad')], default=0, verbose_name='种类')),
                ('version', models.CharField(blank=True, default='', max_length=128, verbose_name='版本')),
                ('manufacturer', models.CharField(blank=True, default='', max_length=256, verbose_name='厂商')),
                ('system', models.CharField(max_length=64, verbose_name='系统')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, '草稿'), (1, '正常'), (2, '无效')], default=1, verbose_name='状态')),
                ('resolution', models.CharField(blank=True, max_length=128, verbose_name='分辨率')),
                ('comment', models.CharField(blank=True, default='', max_length=256, verbose_name='备注')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='持有人')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备列表',
            },
        ),
    ]
